### ISSUE TITLE
inject env variables for corporate proxy

### ISSUE THREAD

**Issue by nckbgov** [apiclarity/apiclarity#113]
If apiclarity needs to run on a cluster behind corporate proxy, wasm post install job fails to complete.

injection of env variables (HTTPS_PROXY, https_proxy, HTTP_PROXY, http_proxy, no_proxy, NO_PROXY) and update git config (git config --global http.proxy, git config --global https.proxy) fixes the issue

**Comment by FrimIdan** [comment]
Hi @nckbgov thanks for the report.
Can you please share what changes needed to be done so we will update the helm templates and values.

**Comment by nckbgov** [comment]
Hi @FrimIdan,

https://github.com/apiclarity/apiclarity/blob/b1f6d4f657cbb9f2ce70355730b873e77c1c94c5/charts/apiclarity/templates/post-install-job-wasm.yaml#L83 needs to have git http(s) config included:

```bash
 git config --global http.proxy http://proxy.acme.com:80 && git config --global https.proxy http://proxy.acme.com:80
 ```

In the current version i ran on an ephemeral pod the following command:

```bash
/bin/bash -c cd /tmp && git config --global http.proxy http://proxy.acme.com:80 && git config --global https.proxy http://proxy.acme.com:80 && git clone -b v0.9.0 https://github.com/apiclarity/apiclarity.git --recurse-submodules && cd apiclarity/wasm-filters && WASM_FILTER_TRACE_BACKEND_ADDRESS=apiclarity-apiclarity.apiclarity.svc.cluster.local ./deploy.sh open5gs
```

**Comment by FrimIdan** [comment]
@nckbgov , ok we can add this line if proxy is used. What about the env variables (HTTPS_PROXY, https_proxy, HTTP_PROXY, http_proxy, no_proxy, NO_PROXY)?

**Comment by nckbgov** [comment]
Good point. In general we inject the 6 variables to all pods.
But for this particular issue only two can be used to update git http.proxy and git https.proxy

**Comment by FrimIdan** [comment]
@nckbgov can you take a look at https://github.com/apiclarity/apiclarity/pull/114 and see if that solves your issue?

**Comment by nckbgov** [comment]
Thanks @FrimIdan, #114 will solve the issue!
