### ISSUE TITLE
Create a helm chart for APIClarity

### ISSUE THREAD

**Issue by akpsgit** [apiclarity/apiclarity#40]
Currently, APIClarity can be installed only using deployment/apiclarity.yaml.
Need to create a helm chart to manage all the components in the deployment yaml, including volumes with consideration of the cloud platform. In addition, need to create a dependency for the Postgres DB (instead of the static spec that was generated using the Postgres helm template).

**Comment by jadiaconu** [comment]
Fixed by dba17adce34d210c8d340c3d9729efdbcaa967c8
