### ISSUE TITLE
"Deployment" type needs to be configurable

### ISSUE THREAD

**Issue by sedkis** [apiclarity/apiclarity#68]
https://github.com/apiclarity/apiclarity/blob/02b3b5d823545ca7f3214e9dab16b9bf18cbc69e/plugins/gateway/tyk/deploy/deploy.sh#L12

this Needs to be configurable as "daemonset" is what the default Tyk Helm Chart is deployed as.

**Comment by fishkerez** [comment]
Hi @sedkis 

We used the installation instructions from [here](https://github.com/TykTechnologies/tyk-oss-k8s-deployment) which uses deployments.
We can definitely add support also for daemonset and make it configurable. 
We are also planning to move the plugin installation to helm so it will be probably done as part of it.

**Comment by sedkis** [comment]
Excellent, thank-you

> Hi @sedkis
> 
> We used the installation instructions from [here](https://github.com/TykTechnologies/tyk-oss-k8s-deployment) which uses deployments. We can definitely add support also for daemonset and make it configurable. We are also planning to move the plugin installation to helm so it will be probably done as part of it.
